UPDATE BLOG_POST 
  SET 
  TITLE = '{TITLE}',
  SUBTITLE = '{SUBTITLE}',
  BODY = '{BODY}',
  IMAGE_SRC = '{IMAGE_SRC}',
  IMAGES = '{IMAGES}',
  META_TITLE = '{META_TITLE}',
  META_DESCRIPTION = '{META_DESCRIPTION}',
  META_KEYWORDS = '{META_KEYWORDS}',
  DATE = '{DATE}',
  LINK = '{LINK}',
  STATUS = {STATUS}
WHERE ID = {ID}