UPDATE PRODUCTS
  SET 
  NAME = '{NAME}',
  DESCRIPTION = '{DESCRIPTION}',
  CHILDS = '{CHILDS}',
  LINK = '{LINK}',
  STATUS = {STATUS},
  IMAGE_SRC = '{IMAGE_SRC}',
  META_TITLE = '{META_TITLE}',
  META_DESCRIPTION = '{META_DESCRIPTION}',
  META_KEYWORDS = '{META_KEYWORDS}'
WHERE ID = {ID}