UPDATE PRODUCTS
  SET 
  CATEGORY_ID = {CATEGORY_ID},
  BEST_SELLER = {BEST_SELLER},
  NAME = '{NAME}',
  PRICE = '{PRICE}',
  SALE = '{SALE}',
  DESCRIPTION = '{DESCRIPTION}',
  IMAGE_SRC = '{IMAGE_SRC}',
  IMAGES = '{IMAGES}',
  META_TITLE = '{META_TITLE}',
  META_DESCRIPTION = '{META_DESCRIPTION}',
  META_KEYWORDS = '{META_KEYWORDS}',
  LINK = '{LINK}',
  STATUS = {STATUS},
  DATE = '{DATE}'
WHERE ID = {ID}